trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/FerhatGec/elite-build.git && cd elite-build
    ./elitebuild --build
  displayName: 'elitebuild'
